
[build-system]
# requires = ["cython == 0.29.9", "numpy", "setuptools >= 35.0.2", "wheel"]
requires = ["cython >= 0.29.9", "numpy", "setuptools >= 35.0.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37", "py38"]
